import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class TradeTabsService {

  public formFields = {
    "holdings": [
      "action",
      "buyAvgPrice",
      "collateralQuantity",
      "collateralValue",
      "daysPnL",
      "exit",
      "haircut",
      "investedValue",
      "ltp",
      "marketValue",
      "netPnL",
      "pledgeQuantity",
      "quantity",
      "sellAvgPrice",
      "t1Quantity",
      "totalHoldingQ",
      "type",
      "usedQty"
    ],
    "orderBook": [
      "action",
      "avgPrice",
      "date",
      "executedAt",
      "exchangeOrderNo",
      "ltp",
      "orderPrice",
      "orderType",
      "product",
      "qtyFilled",
      "status",
      "symbol",
      "validity",
      "xtsOrderId"
    ],
    "position": [
      "action",
      "buyAvgPrice",
      "buyQty",
      "buyValue",
      "dayPnL",
      "exit",
      "ltp",
      "netAvg",
      "netPnL",
      "netQty",
      "netValue",
      "product",
      "realizedMtm",
      "sellAvgPrice",
      "sellQty",
      "sellValue",
      "symbol",
      "totalTurnover",
      "type",
      "unrealizedMtm"
    ],
    "tradeBook": [
      "action",
      "avgPrice",
      "exchangeOrderNo",
      "ltp",
      "orderNo",
      "orderType",
      "product",
      "qtyFilled",
      "status",
      "symbol",
      "tradedAt",
      "type"
    ]
  }
  ;
  public sampleDataSet = {
    holdings: [
      {
        symbol: "AAPL",
        type: "SELL",
        quantity: "751/0",
        t1Quantity: "0",
        usedQty: "0",
        daysPnL: "0.00",
        netPnL: "0.00",
        buyAvgPrice: "0.00",
        ltp: "0.00",
        totalHoldingQ: "0",
        sellAvgPrice: "4094.63",
        investedValue: "0.00",
        marketValue: "0.00",
        haircut: "0.00",
        collateralQuantity: "0",
        pledgeQuantity: "0",
        collateralValue: "0.00",
        action: "",
        exit: ""
      },
      {
        symbol: "AMZN",
        type: "SELL",
        quantity: "385/0",
        t1Quantity: "0",
        usedQty: "0",
        daysPnL: "0.00",
        netPnL: "0.00",
        buyAvgPrice: "0.00",
        ltp: "0.00",
        totalHoldingQ: "0",
        sellAvgPrice: "1494.04",
        investedValue: "0.00",
        marketValue: "0.00",
        haircut: "0.00",
        collateralQuantity: "0",
        pledgeQuantity: "0",
        collateralValue: "0.00",
        action: "",
        exit: ""
      },
      {
        symbol: "TSLA",
        type: "SELL",
        quantity: "134/0",
        t1Quantity: "0",
        usedQty: "0",
        daysPnL: "0.00",
        netPnL: "0.00",
        buyAvgPrice: "0.00",
        ltp: "0.00",
        totalHoldingQ: "0",
        sellAvgPrice: "2978.91",
        investedValue: "0.00",
        marketValue: "0.00",
        haircut: "0.00",
        collateralQuantity: "0",
        pledgeQuantity: "0",
        collateralValue: "0.00",
        action: "",
        exit: ""
      },
      {
        symbol: "TSLA",
        type: "BUY",
        quantity: "651/0",
        t1Quantity: "0",
        usedQty: "0",
        daysPnL: "0.00",
        netPnL: "0.00",
        buyAvgPrice: "4803.50",
        ltp: "0.00",
        totalHoldingQ: "0",
        sellAvgPrice: "0.00",
        investedValue: "0.00",
        marketValue: "0.00",
        haircut: "0.00",
        collateralQuantity: "0",
        pledgeQuantity: "0",
        collateralValue: "0.00",
        action: "",
        exit: ""
      },
      {
        symbol: "AAPL",
        type: "SELL",
        quantity: "44/0",
        t1Quantity: "0",
        usedQty: "0",
        daysPnL: "0.00",
        netPnL: "0.00",
        buyAvgPrice: "0.00",
        ltp: "0.00",
        totalHoldingQ: "0",
        sellAvgPrice: "3079.43",
        investedValue: "0.00",
        marketValue: "0.00",
        haircut: "0.00",
        collateralQuantity: "0",
        pledgeQuantity: "0",
        collateralValue: "0.00",
        action: "",
        exit: ""
      },
      {
        symbol: "AMZN",
        type: "BUY",
        quantity: "745/0",
        t1Quantity: "0",
        usedQty: "0",
        daysPnL: "0.00",
        netPnL: "0.00",
        buyAvgPrice: "2882.63",
        ltp: "0.00",
        totalHoldingQ: "0",
        sellAvgPrice: "0.00",
        investedValue: "0.00",
        marketValue: "0.00",
        haircut: "0.00",
        collateralQuantity: "0",
        pledgeQuantity: "0",
        collateralValue: "0.00",
        action: "",
        exit: ""
      },
      {
        symbol: "MSFT",
        type: "BUY",
        quantity: "121/0",
        t1Quantity: "0",
        usedQty: "0",
        daysPnL: "0.00",
        netPnL: "0.00",
        buyAvgPrice: "4660.78",
        ltp: "0.00",
        totalHoldingQ: "0",
        sellAvgPrice: "0.00",
        investedValue: "0.00",
        marketValue: "0.00",
        haircut: "0.00",
        collateralQuantity: "0",
        pledgeQuantity: "0",
        collateralValue: "0.00",
        action: "",
        exit: ""
      },
      {
        symbol: "TSLA",
        type: "SELL",
        quantity: "183/0",
        t1Quantity: "0",
        usedQty: "0",
        daysPnL: "0.00",
        netPnL: "0.00",
        buyAvgPrice: "0.00",
        ltp: "0.00",
        totalHoldingQ: "0",
        sellAvgPrice: "4060.68",
        investedValue: "0.00",
        marketValue: "0.00",
        haircut: "0.00",
        collateralQuantity: "0",
        pledgeQuantity: "0",
        collateralValue: "0.00",
        action: "",
        exit: ""
      },
      {
        symbol: "TSLA",
        type: "BUY",
        quantity: "382/0",
        t1Quantity: "0",
        usedQty: "0",
        daysPnL: "0.00",
        netPnL: "0.00",
        buyAvgPrice: "4019.24",
        ltp: "0.00",
        totalHoldingQ: "0",
        sellAvgPrice: "0.00",
        investedValue: "0.00",
        marketValue: "0.00",
        haircut: "0.00",
        collateralQuantity: "0",
        pledgeQuantity: "0",
        collateralValue: "0.00",
        action: "",
        exit: ""
      },
      {
        symbol: "TSLA",
        type: "SELL",
        quantity: "89/0",
        t1Quantity: "0",
        usedQty: "0",
        daysPnL: "0.00",
        netPnL: "0.00",
        buyAvgPrice: "0.00",
        ltp: "0.00",
        totalHoldingQ: "0",
        sellAvgPrice: "1478.39",
        investedValue: "0.00",
        marketValue: "0.00",
        haircut: "0.00",
        collateralQuantity: "0",
        pledgeQuantity: "0",
        collateralValue: "0.00",
        action: "",
        exit: ""
      }
    ],
    orderBook: [
      { symbol: "Sunil Joshi", type: "SELL", qtyFilled: "751/0", orderPrice: "4094.63", executedAt: "0.00", avgPrice: "0.00", ltp: "0.00", status: "REJECTED", date: "02/02/2025 17:08:14", validity: "DAY", product: "MIS", orderType: "LIMIT", xtsOrderId: "554794014", exchangeOrderNo: "", action: "" },
      { symbol: "AMZN", type: "SELL", qtyFilled: "385/0", orderPrice: "1494.04", executedAt: "0.00", avgPrice: "0.00", ltp: "0.00", status: "PARTIALLY EXECUTED", date: "07/02/2025 07:05:22", validity: "DAY", product: "BRR", orderType: "LIMIT", xtsOrderId: "436310558", exchangeOrderNo: "", action: "" },
      { symbol: "TSLA", type: "SELL", qtyFilled: "134/0", orderPrice: "2978.91", executedAt: "0.00", avgPrice: "0.00", ltp: "0.00", status: "CANCELLED", date: "06/02/2025 13:31:59", validity: "DAY", product: "NRM", orderType: "STOP", xtsOrderId: "700340716", exchangeOrderNo: "", action: "" },
      { symbol: "TSLA", type: "BUY", qtyFilled: "651/0", orderPrice: "4803.50", executedAt: "0.00", avgPrice: "0.00", ltp: "0.00", status: "CANCELLED", date: "01/02/2025 05:09:15", validity: "DAY", product: "NRM", orderType: "MARKET", xtsOrderId: "460387226", exchangeOrderNo: "", action: "" },
      { symbol: "AAPL", type: "SELL", qtyFilled: "44/0", orderPrice: "3079.43", executedAt: "0.00", avgPrice: "0.00", ltp: "0.00", status: "CANCELLED", date: "09/02/2025 17:56:53", validity: "DAY", product: "NRM", orderType: "MARKET", xtsOrderId: "637209172", exchangeOrderNo: "", action: "" },
      { symbol: "AMZN", type: "BUY", qtyFilled: "745/0", orderPrice: "2882.63", executedAt: "0.00", avgPrice: "0.00", ltp: "0.00", status: "PARTIALLY EXECUTED", date: "15/02/2025 22:18:16", validity: "DAY", product: "MIS", orderType: "STOP", xtsOrderId: "732346546", exchangeOrderNo: "", action: "" },
      { symbol: "MSFT", type: "BUY", qtyFilled: "121/0", orderPrice: "4660.78", executedAt: "0.00", avgPrice: "0.00", ltp: "0.00", status: "PARTIALLY EXECUTED", date: "02/02/2025 01:04:44", validity: "DAY", product: "MIS", orderType: "STOP", xtsOrderId: "591150188", exchangeOrderNo: "", action: "" },
      { symbol: "TSLA", type: "SELL", qtyFilled: "183/0", orderPrice: "4060.68", executedAt: "0.00", avgPrice: "0.00", ltp: "0.00", status: "PARTIALLY EXECUTED", date: "31/01/2025 17:21:12", validity: "DAY", product: "MIS", orderType: "STOP", xtsOrderId: "886728085", exchangeOrderNo: "", action: "" },
      { symbol: "TSLA", type: "BUY", qtyFilled: "382/0", orderPrice: "4019.24", executedAt: "0.00", avgPrice: "0.00", ltp: "0.00", status: "EXECUTED", date: "14/02/2025 10:06:47", validity: "DAY", product: "BRR", orderType: "MARKET", xtsOrderId: "816087944", exchangeOrderNo: "", action: "" },
      { symbol: "TSLA", type: "SELL", qtyFilled: "89/0", orderPrice: "1478.39", executedAt: "0.00", avgPrice: "0.00", ltp: "0.00", status: "REJECTED", date: "01/02/2025 18:39:14", validity: "DAY", product: "BRR", orderType: "LIMIT", xtsOrderId: "749847732", exchangeOrderNo: "", action: "" }
    ],
    position: [
      {
        symbol: "AAPL",
        type: "SELL",
        product: "MIS",
        buyQty: "751/0",
        buyAvgPrice: "4094.63",
        buyValue: "0.00",
        ltp: "0.00",
        dayPnL: "0.00",
        netPnL: "REJECTED",
        netAvg: "02/02/2025 17:08:14",
        netQty: "DAY",
        netValue: "LIMIT",
        totalTurnover: "554794014",
        sellQty: "",
        sellAvgPrice: "",
        sellValue: "",
        realizedMtm: "",
        unrealizedMtm: "",
        action: "",
        exit: ""
      },
      {
        symbol: "AMZN",
        type: "SELL",
        product: "BRR",
        buyQty: "385/0",
        buyAvgPrice: "1494.04",
        buyValue: "0.00",
        ltp: "0.00",
        dayPnL: "0.00",
        netPnL: "PARTIALLY EXECUTED",
        netAvg: "07/02/2025 07:05:22",
        netQty: "DAY",
        netValue: "LIMIT",
        totalTurnover: "436310558",
        sellQty: "",
        sellAvgPrice: "",
        sellValue: "",
        realizedMtm: "",
        unrealizedMtm: "",
        action: "",
        exit: ""
      },
      {
        symbol: "TSLA",
        type: "SELL",
        product: "NRM",
        buyQty: "134/0",
        buyAvgPrice: "2978.91",
        buyValue: "0.00",
        ltp: "0.00",
        dayPnL: "0.00",
        netPnL: "CANCELLED",
        netAvg: "06/02/2025 13:31:59",
        netQty: "DAY",
        netValue: "STOP",
        totalTurnover: "700340716",
        sellQty: "",
        sellAvgPrice: "",
        sellValue: "",
        realizedMtm: "",
        unrealizedMtm: "",
        action: "",
        exit: ""
      },
      {
        symbol: "TSLA",
        type: "BUY",
        product: "NRM",
        buyQty: "651/0",
        buyAvgPrice: "4803.50",
        buyValue: "0.00",
        ltp: "0.00",
        dayPnL: "0.00",
        netPnL: "CANCELLED",
        netAvg: "01/02/2025 05:09:15",
        netQty: "DAY",
        netValue: "MARKET",
        totalTurnover: "460387226",
        sellQty: "",
        sellAvgPrice: "",
        sellValue: "",
        realizedMtm: "",
        unrealizedMtm: "",
        action: "",
        exit: ""
      },
      {
        symbol: "AAPL",
        type: "SELL",
        product: "NRM",
        buyQty: "44/0",
        buyAvgPrice: "3079.43",
        buyValue: "0.00",
        ltp: "0.00",
        dayPnL: "0.00",
        netPnL: "CANCELLED",
        netAvg: "09/02/2025 17:56:53",
        netQty: "DAY",
        netValue: "MARKET",
        totalTurnover: "637209172",
        sellQty: "",
        sellAvgPrice: "",
        sellValue: "",
        realizedMtm: "",
        unrealizedMtm: "",
        action: "",
        exit: ""
      },
      {
        symbol: "AMZN",
        type: "BUY",
        product: "MIS",
        buyQty: "745/0",
        buyAvgPrice: "2882.63",
        buyValue: "0.00",
        ltp: "0.00",
        dayPnL: "0.00",
        netPnL: "PARTIALLY EXECUTED",
        netAvg: "15/02/2025 22:18:16",
        netQty: "DAY",
        netValue: "STOP",
        totalTurnover: "732346546",
        sellQty: "",
        sellAvgPrice: "",
        sellValue: "",
        realizedMtm: "",
        unrealizedMtm: "",
        action: "",
        exit: ""
      },
      {
        symbol: "MSFT",
        type: "BUY",
        product: "MIS",
        buyQty: "121/0",
        buyAvgPrice: "4660.78",
        buyValue: "0.00",
        ltp: "0.00",
        dayPnL: "0.00",
        netPnL: "PARTIALLY EXECUTED",
        netAvg: "02/02/2025 01:04:44",
        netQty: "DAY",
        netValue: "STOP",
        totalTurnover: "591150188",
        sellQty: "",
        sellAvgPrice: "",
        sellValue: "",
        realizedMtm: "",
        unrealizedMtm: "",
        action: "",
        exit: ""
      },
      {
        symbol: "TSLA",
        type: "SELL",
        product: "MIS",
        buyQty: "183/0",
        buyAvgPrice: "4060.68",
        buyValue: "0.00",
        ltp: "0.00",
        dayPnL: "0.00",
        netPnL: "PARTIALLY EXECUTED",
        netAvg: "31/01/2025 17:21:12",
        netQty: "DAY",
        netValue: "STOP",
        totalTurnover: "886728085",
        sellQty: "",
        sellAvgPrice: "",
        sellValue: "",
        realizedMtm: "",
        unrealizedMtm: "",
        action: "",
        exit: ""
      },
      {
        symbol: "TSLA",
        type: "BUY",
        product: "BRR",
        buyQty: "382/0",
        buyAvgPrice: "4019.24",
        buyValue: "0.00",
        ltp: "0.00",
        dayPnL: "0.00",
        netPnL: "EXECUTED",
        netAvg: "14/02/2025 10:06:47",
        netQty: "DAY",
        netValue: "MARKET",
        totalTurnover: "816087944",
        sellQty: "",
        sellAvgPrice: "",
        sellValue: "",
        realizedMtm: "",
        unrealizedMtm: "",
        action: "",
        exit: ""
      },
      {
        symbol: "TSLA",
        type: "SELL",
        product: "BRR",
        buyQty: "89/0",
        buyAvgPrice: "1478.39",
        buyValue: "0.00",
        ltp: "0.00",
        dayPnL: "0.00",
        netPnL: "REJECTED",
        netAvg: "01/02/2025 18:39:14",
        netQty: "DAY",
        netValue: "LIMIT",
        totalTurnover: "749847732",
        sellQty: "",
        sellAvgPrice: "",
        sellValue: "",
        realizedMtm: "",
        unrealizedMtm: "",
        action: "",
        exit: ""
      }
    ],
    tradeBook: [
      {
        symbol: "AMZN",
        type: "SELL",
        qtyFilled: "759/833",
        avgPrice: "3528.26",
        product: "NRM",
        orderType: "LIMIT",
        status: "EXECUTED",
        orderNo: "ORD98464",
        exchangeOrderNo: "EXCH916970",
        ltp: "4190.42",
        tradedAt: "15/02/2025 04:31:36",
        action: ["Buy"]
      },
      {
        symbol: "MSFT",
        type: "BUY",
        qtyFilled: "683/514",
        avgPrice: "4701.39",
        product: "MIS",
        orderType: "MARKET",
        status: "EXECUTED",
        orderNo: "ORD709132",
        exchangeOrderNo: "EXCH734882",
        ltp: "3438.11",
        tradedAt: "20/02/2025 18:21:48",
        action: ["Buy"]
      }
      // Add more trade records here as needed...
    ]
  }
  constructor() { }
}